# Expert option questionnaire

In [83]:
import pandas as pd
import numpy as np
print("Imported")

Imported


## Part 1

In [84]:
A = [0,2,2,1,3,3,3,0]
B = [7,5,2,7,2,2,0,1]
d = {'A': A, 'B': B}
df = pd.DataFrame(data = d)
print(df)

   A  B
0  0  7
1  2  5
2  2  2
3  1  7
4  3  2
5  3  2
6  3  0
7  0  1


## a) log1p

In [85]:
Alog1p = np.log1p(df.A)
print(Alog1p)

0    0.000000
1    1.098612
2    1.098612
3    0.693147
4    1.386294
5    1.386294
6    1.386294
7    0.000000
Name: A, dtype: float64


## b)  row-wise maximum

In [86]:
print('Using numpy function')
print(np.max(df, axis = 1), 3*'\n')
# or 
print('Using pandas method')
print(df.max(axis = 1))

Using numpy function
0    7
1    5
2    2
3    7
4    3
5    3
6    3
7    1
dtype: int64 



Using pandas method
0    7
1    5
2    2
3    7
4    3
5    3
6    3
7    1
dtype: int64


## c) sorted row number

In [87]:
"""
Sorting, resetting index while saving the old one as a column, 
sorting back by the index column I saved and extracting the index.
This will give us the row number which the element would have if sorted.
I'm adding one to make them start with 1 rather than with 0
"""
C = df.A.sort_values(ascending = True).reset_index(inplace = False)
C1 = C.sort_values('index')

#to better represent it 
ans = pd.DataFrame({"A": df['A'],"row_number": pd.Series(C1.index)+1})
print(ans.to_string(index = False))


 A  row_number
 0           1
 2           4
 2           5
 1           3
 3           6
 3           7
 3           8
 0           2


## d) Max b for each unique a

In [88]:
d = pd.DataFrame(df.groupby('A').max().reset_index())
print(d.to_string(index = False))

 A  B
 0  7
 1  7
 2  5
 3  2


In [89]:
#or if it's necessary to keep duplicates
d1 = df[df['B'] == df.groupby('A')['B'].transform('max')].sort_values('A')
print(d1.to_string(index = False))

 A  B
 0  7
 1  7
 2  5
 3  2
 3  2


## Part 2

In [90]:
arr = np.random.randint(low = 1,high = 10000, size = (5,100000))
print(arr)

[[5876 3174 6729 ... 5689 1864 8792]
 [5180 8894 9011 ... 1874 5432 4169]
 [ 356 4151 9424 ... 7111 9491 3866]
 [4193 6637 5191 ...  857 5864 9025]
 [1474  650 6584 ... 6626 2378 9023]]


## a) row-wise maximum

In [91]:
print(np.max(arr, axis = 1))

[9999 9999 9999 9999 9999]


## b) column-wise maximum

In [92]:
np.max(arr, axis = 0)

array([5876, 8894, 9424, ..., 7111, 9491, 9025])

## c) array from every 3rd row

In [93]:
#this selects rows 0,3,6,9 and so on (in our case just 0 and 3)
ndarray = arr[::3]
print(ndarray)


# if we need to start counting rows from 1 and 
#select rows 3,6,9,12 and so on the solution slightly differs

[[5876 3174 6729 ... 5689 1864 8792]
 [4193 6637 5191 ...  857 5864 9025]]


In [94]:
# if we need to start counting rows from 1 and select rows 3,6,9,12 and so on (just the 3rd in our case)

ndarray3rd = arr[2::3]
print(ndarray3rd)

[[ 356 4151 9424 ... 7111 9491 3866]]


Done