# Expert option questionnaire

In [59]:
import pandas as pd
import numpy as np
print("Imported")

Imported


## Part 1

In [60]:
#1
A = [0,2,2,1,3,3,3,0]
B = [7,5,2,7,2,2,0,1]
d = {'A': A, 'B': B}
df = pd.DataFrame(data = d)
print(df)

   A  B
0  0  7
1  2  5
2  2  2
3  1  7
4  3  2
5  3  2
6  3  0
7  0  1


## a

In [61]:
Alog1p = np.log1p(df.A)
print(Alog1p)

0    0.000000
1    1.098612
2    1.098612
3    0.693147
4    1.386294
5    1.386294
6    1.386294
7    0.000000
Name: A, dtype: float64


## b

In [62]:
print('Using numpy function')
print(np.max(df, axis = 1),3*'\n')
# or 
print('Using pandas method')
print(df.max(axis = 1))

Using numpy function
0    7
1    5
2    2
3    7
4    3
5    3
6    3
7    1
dtype: int64 



Using pandas method
0    7
1    5
2    2
3    7
4    3
5    3
6    3
7    1
dtype: int64


## c

In [63]:
"""Sorting, resetting index while saving the old one as a column, 
sorting back by the index column I saved and extracting the index.
This will give us the row number which the element would have if sorted.
I'm adding one to make them start with 1 rather than with 0
"""
C = df.A.sort_values(ascending = True).reset_index(inplace = False)
C1 = C.sort_values('index')
print((pd.Series(C1.index)+1).to_string(index = False))


#to better represent it 
ans = pd.DataFrame({"A": df['A'],"row_number": pd.Series(C1.index)+1})
print(ans.to_string(index = False))


 1
 4
 5
 3
 6
 7
 8
 2
 A  row_number
 0           1
 2           4
 2           5
 1           3
 3           6
 3           7
 3           8
 0           2


## d

In [64]:
d = pd.DataFrame(df.groupby('A').max().reset_index())
print(d.to_string(index = False))

 A  B
 0  7
 1  7
 2  5
 3  2


In [65]:
#or if it's necessary to keep duplicates
d1 = df[df['B'] == df.groupby('A')['B'].transform('max')].sort_values('A')
print(d1.to_string(index = False))

 A  B
 0  7
 1  7
 2  5
 3  2
 3  2


## Part 2

In [66]:
arr = np.random.randint(low = 1,high = 10000, size = (5,100000))
print(arr)

[[ 615 3872 3441 ... 2859 6074 8052]
 [6124 1448 6578 ... 5834  227 8629]
 [6723 7531 3878 ... 6722 4363 8559]
 [4393 5754 6528 ... 4638 2505  127]
 [8604 1965 4472 ... 2521 1345 8572]]


## a

In [67]:
#a
np.max(arr, axis = 1)

array([9999, 9999, 9999, 9999, 9999])

## b

In [68]:
#b
np.max(arr, axis = 0)

array([8604, 7531, 6578, ..., 6722, 6074, 8629])

## c

In [69]:
#c
#Normally that would be a solution 
ndarray = arr[::3]
print(ndarray)

#this selects rows 0,3,6,9 and so on
# if we need to start counting rows from 1 and select rows 3,6,9,12 the solution slightly differs

[[ 615 3872 3441 ... 2859 6074 8052]
 [4393 5754 6528 ... 4638 2505  127]]


In [70]:
# if we need to start counting rows from 1 and select rows 3,6,9,12 and so on
# then I would just start the array from the 3rd row

ndarray3rd = arr[2::3]
print(ndarray3rd)

[[6723 7531 3878 ... 6722 4363 8559]]


Done

In [71]:
#if needed to print without index 
print(d.to_string(index = False))

 A  B
 0  7
 1  7
 2  5
 3  2
