In [90]:
#Questionnaire
import pandas as pd
import numpy as np

In [104]:
#1
A = [0,2,2,1,3,3,3,0]
B = [7,5,2,7,2,2,0,1]
d = {'A': A, 'B': B}
data = pd.DataFrame(data = d)
print(data)

   A  B
0  0  7
1  2  5
2  2  2
3  1  7
4  3  2
5  3  2
6  3  0
7  0  1


In [150]:
#a)
Alog1p = np.log1p(data.A)
print(Alog1p)

0    0.000000
1    1.098612
2    1.098612
3    0.693147
4    1.386294
5    1.386294
6    1.386294
7    0.000000
Name: A, dtype: float64


In [153]:
#b)
print(np.max(data, axis = 1),'2*\n')
# or 
print(data.max(axis = 1))

0    7
1    5
2    2
3    7
4    3
5    3
6    3
7    1
dtype: int64 2*

0    7
1    5
2    2
3    7
4    3
5    3
6    3
7    1
dtype: int64


In [143]:
#c) 
"""Sorting, resetting index saving the old one as a column, 
sorting back by the index column I saved and extracting the index.
This will give us the row number which the element would have if sorted 
I'm adding one to make them start with 1 rather than with 0
"""
C = data.A.sort_values(ascending = True).reset_index(inplace = False)
C1 = C.sort_values('index')
print((pd.Series(C1.index)+1).to_string(index = False))


 1
 4
 5
 3
 6
 7
 8
 2


In [148]:
#to better represent it 
ans = pd.DataFrame({"A": data['A'],"row_number": pd.Series(C1.index)+1})
print(ans.to_string(index = False))

 A  row_number
 0           1
 2           4
 2           5
 1           3
 3           6
 3           7
 3           8
 0           2


In [95]:
#d)
d = pd.DataFrame(data.groupby('A').max().reset_index())
print(d)

   A  B
0  0  7
1  1  7
2  2  5
3  3  2


In [96]:
#if needed to print without index 
print(d.to_string(index = False))

 A  B
 0  7
 1  7
 2  5
 3  2


In [97]:
# Part 2

In [156]:
arr = np.random.randint(low = 1,high = 10000, size = (5,100000))
print(arr)

[[2470 8937 2740 ... 2455 5829 3126]
 [4632 2596 6064 ... 7221 4377 1869]
 [5517 2053 3519 ... 6632 2419  473]
 [1148 6795 2120 ... 9567  328 7934]
 [6239 6853 8654 ...   74 7223  193]]


In [157]:
#a
np.max(arr, axis = 1)

array([9999, 9999, 9999, 9999, 9999])

In [158]:
#b
np.max(arr, axis = 0)

array([6239, 8937, 8654, ..., 9567, 7223, 7934])

In [102]:
#c
#Normally that would be a solution 
ndarray = arr[::3]
print(ndarray)

#this selects rows 0,3,6,9 and so on
# if we need to start counting rows from 1 and select rows 3,6,9,12 the solution slightly differs

[[13600  1475 19550 ... 19040 19780 19124]
 [15168  9353  3748 ... 10638  7140  5172]]


In [103]:
# if we need to start counting rows from 1 and select rows 3,6,9,12 and so on
# then I would just start the array from the 3rd row

ndarray3rd = arr[2::3]
print(ndarray3rd)

[[13985 13852  1405 ... 15495 13652 18186]]
