In [15]:
#Questionnaire
import pandas as pd
import numpy as np
print("Imported")

Imported


In [16]:
#1
A = [0,2,2,1,3,3,3,0]
B = [7,5,2,7,2,2,0,1]
d = {'A': A, 'B': B}
df = pd.DataFrame(data = d)
print(df)

   A  B
0  0  7
1  2  5
2  2  2
3  1  7
4  3  2
5  3  2
6  3  0
7  0  1


In [17]:
#a)
Alog1p = np.log1p(df.A)
print(Alog1p)

0    0.000000
1    1.098612
2    1.098612
3    0.693147
4    1.386294
5    1.386294
6    1.386294
7    0.000000
Name: A, dtype: float64


In [30]:
#b)
print(np.max(df, axis = 1),3*'\n')
# or 
print(df.max(axis = 1))

0    7
1    5
2    2
3    7
4    3
5    3
6    3
7    1
dtype: int64 



0    7
1    5
2    2
3    7
4    3
5    3
6    3
7    1
dtype: int64


In [19]:
#c) 
"""Sorting, resetting index saving the old one as a column, 
sorting back by the index column I saved and extracting the index.
This will give us the row number which the element would have if sorted 
I'm adding one to make them start with 1 rather than with 0
"""
C = df.A.sort_values(ascending = True).reset_index(inplace = False)
C1 = C.sort_values('index')
print((pd.Series(C1.index)+1).to_string(index = False))


 1
 4
 5
 3
 6
 7
 8
 2


In [20]:
#to better represent it 
ans = pd.DataFrame({"A": df['A'],"row_number": pd.Series(C1.index)+1})
print(ans.to_string(index = False))

 A  row_number
 0           1
 2           4
 2           5
 1           3
 3           6
 3           7
 3           8
 0           2


In [21]:
#d)
d = pd.DataFrame(df.groupby('A').max().reset_index())
print(d)

   A  B
0  0  7
1  1  7
2  2  5
3  3  2


In [22]:
#if needed to print without index 
print(d.to_string(index = False))

 A  B
 0  7
 1  7
 2  5
 3  2


In [23]:
# Part 2

In [24]:
arr = np.random.randint(low = 1,high = 10000, size = (5,100000))
print(arr)

[[9414  490 6518 ... 4849 1352 7258]
 [7503 5111 6642 ...  140 2602 9819]
 [4994 5419 8672 ... 6882 1484  548]
 [6345 5457 8995 ... 8146 3528 2763]
 [3108 3058 9215 ... 7175  871 8432]]


In [25]:
#a
np.max(arr, axis = 1)

array([9999, 9999, 9999, 9999, 9999])

In [26]:
#b
np.max(arr, axis = 0)

array([9414, 5457, 9215, ..., 8146, 3528, 9819])

In [27]:
#c
#Normally that would be a solution 
ndarray = arr[::3]
print(ndarray)

#this selects rows 0,3,6,9 and so on
# if we need to start counting rows from 1 and select rows 3,6,9,12 the solution slightly differs

[[9414  490 6518 ... 4849 1352 7258]
 [6345 5457 8995 ... 8146 3528 2763]]


In [28]:
# if we need to start counting rows from 1 and select rows 3,6,9,12 and so on
# then I would just start the array from the 3rd row

ndarray3rd = arr[2::3]
print(ndarray3rd)

[[4994 5419 8672 ... 6882 1484  548]]


Done